In [151]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn import tree
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_predict
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import cross_val_score


# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.

['FIFA 2018 Statistics.csv']


# Visaulization of Data

In [115]:
df=pd.read_csv('../input/FIFA 2018 Statistics.csv')
df.head()

Date          Team      ...       Own goals  Own goal Time
0  14-06-2018        Russia      ...             NaN            NaN
1  14-06-2018  Saudi Arabia      ...             NaN            NaN
2  15-06-2018         Egypt      ...             NaN            NaN
3  15-06-2018       Uruguay      ...             NaN            NaN
4  15-06-2018       Morocco      ...             1.0           90.0

[5 rows x 27 columns]

In [116]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 27 columns):
Date                      128 non-null object
Team                      128 non-null object
Opponent                  128 non-null object
Goal Scored               128 non-null int64
Ball Possession %         128 non-null int64
Attempts                  128 non-null int64
On-Target                 128 non-null int64
Off-Target                128 non-null int64
Blocked                   128 non-null int64
Corners                   128 non-null int64
Offsides                  128 non-null int64
Free Kicks                128 non-null int64
Saves                     128 non-null int64
Pass Accuracy %           128 non-null int64
Passes                    128 non-null int64
Distance Covered (Kms)    128 non-null int64
Fouls Committed           128 non-null int64
Yellow Card               128 non-null int64
Yellow & Red              128 non-null int64
Red                       128 non-nul

In [117]:
#dummy=pd.get_dummies(df.loc[:,'Man of the Match'])
#df=df.merge(dummy,left_index=True,right_index=True)
df.head()

Date          Team      ...       Own goals  Own goal Time
0  14-06-2018        Russia      ...             NaN            NaN
1  14-06-2018  Saudi Arabia      ...             NaN            NaN
2  15-06-2018         Egypt      ...             NaN            NaN
3  15-06-2018       Uruguay      ...             NaN            NaN
4  15-06-2018       Morocco      ...             1.0           90.0

[5 rows x 27 columns]

In [118]:
df.corr()

Goal Scored      ...        Own goal Time
Goal Scored                1.000000      ...            -0.228729
Ball Possession %          0.034759      ...             0.588196
Attempts                   0.144915      ...            -0.012727
On-Target                  0.461702      ...            -0.328175
Off-Target                -0.020374      ...             0.300204
Blocked                   -0.087072      ...             0.014851
Corners                    0.040446      ...             0.023942
Offsides                   0.045105      ...            -0.312680
Free Kicks                 0.046815      ...            -0.057103
Saves                     -0.118893      ...            -0.063865
Pass Accuracy %            0.135688      ...             0.390021
Passes                     0.043971      ...             0.296754
Distance Covered (Kms)     0.014355      ...            -0.313181
Fouls Committed            0.030331      ...             0.002941
Yellow Card               -0.048838      ...             0.319416
Yellow & Red              -0.035031      ...            -0.239862
Red                       -0.089714      ...                  NaN
1st Goal                  -0.272170      ...             0.332835
Goals in PSO              -0.011204      ...            -0.355415
Own goals                       NaN      ...                  NaN
Own goal Time             -0.228729      ...             1.000000

[21 rows x 21 columns]

In [119]:
df.describe()

Goal Scored  Ball Possession %      ...        Own goals  Own goal Time
count   128.000000         128.000000      ...             12.0      12.000000
mean      1.320312          49.992188      ...              1.0      45.833333
std       1.156519          10.444074      ...              0.0      29.978275
min       0.000000          25.000000      ...              1.0      12.000000
25%       0.000000          42.000000      ...              1.0      21.750000
50%       1.000000          50.000000      ...              1.0      35.000000
75%       2.000000          58.000000      ...              1.0      75.750000
max       6.000000          75.000000      ...              1.0      90.000000

[8 rows x 21 columns]

In [120]:
df.isnull().sum()

Date                        0
Team                        0
Opponent                    0
Goal Scored                 0
Ball Possession %           0
Attempts                    0
On-Target                   0
Off-Target                  0
Blocked                     0
Corners                     0
Offsides                    0
Free Kicks                  0
Saves                       0
Pass Accuracy %             0
Passes                      0
Distance Covered (Kms)      0
Fouls Committed             0
Yellow Card                 0
Yellow & Red                0
Red                         0
Man of the Match            0
1st Goal                   34
Round                       0
PSO                         0
Goals in PSO                0
Own goals                 116
Own goal Time             116
dtype: int64

### since, the columns "own goals, own goal time, and 1st goal have 90% missing values. so rather we will drop these columns"

In [121]:
for col in df.columns:
    col.rstrip()

## One hot encoding is done here after droping and cleaning the data as necessary

In [122]:
tree = DecisionTreeClassifier()
df.drop(['Own goal Time', 'Own goals', '1st Goal'], axis = 1, inplace= True)
df.drop(['Corners', 'Fouls Committed', 'On-Target'], axis = 1, inplace=True)
df.drop('Date', axis = 1, inplace=True)
one_hot_data = pd.get_dummies(df,drop_first=True)
#one_hot_data.head()
one_hot_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 84 columns):
Goal Scored                128 non-null int64
Ball Possession %          128 non-null int64
Attempts                   128 non-null int64
Off-Target                 128 non-null int64
Blocked                    128 non-null int64
Offsides                   128 non-null int64
Free Kicks                 128 non-null int64
Saves                      128 non-null int64
Pass Accuracy %            128 non-null int64
Passes                     128 non-null int64
Distance Covered (Kms)     128 non-null int64
Yellow Card                128 non-null int64
Yellow & Red               128 non-null int64
Red                        128 non-null int64
Goals in PSO               128 non-null int64
Team_Australia             128 non-null uint8
Team_Belgium               128 non-null uint8
Team_Brazil                128 non-null uint8
Team_Colombia              128 non-null uint8
Team_Costa Rica      

In [123]:
#one_hot_data.dropna(inplace=True)
#tree.fit(one_hot_data, one_hot_data.loc[:,'PSO_Yes'])

In [124]:
one_hot_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 84 columns):
Goal Scored                128 non-null int64
Ball Possession %          128 non-null int64
Attempts                   128 non-null int64
Off-Target                 128 non-null int64
Blocked                    128 non-null int64
Offsides                   128 non-null int64
Free Kicks                 128 non-null int64
Saves                      128 non-null int64
Pass Accuracy %            128 non-null int64
Passes                     128 non-null int64
Distance Covered (Kms)     128 non-null int64
Yellow Card                128 non-null int64
Yellow & Red               128 non-null int64
Red                        128 non-null int64
Goals in PSO               128 non-null int64
Team_Australia             128 non-null uint8
Team_Belgium               128 non-null uint8
Team_Brazil                128 non-null uint8
Team_Colombia              128 non-null uint8
Team_Costa Rica      

# Function to calculate Accuracy as well as confusion matrix for the results

In [125]:
def cal_accuracy(y_test, y_pred): 
      
    print("Confusion Matrix: ", 
        confusion_matrix(y_test, y_pred)) 
      
    print ("Accuracy : ", 
    accuracy_score(y_test,y_pred)*100) 
      
    print("Report : ", 
    classification_report(y_test, y_pred))

In [126]:
#idx = pd.IndexSlice
#one_hot_data.fillna(one_hot_data['Own goal Time'].mean(),inplace=True)
#one_hot_data.fillna(value=0,inplace=True)

In [127]:
one_hot_data.isnull().values.any()

False

In [128]:
one_hot_data.head()

Goal Scored  Ball Possession %   ...     Round_Semi- Finals  PSO_Yes
0            5                 40   ...                      0        0
1            0                 60   ...                      0        0
2            0                 43   ...                      0        0
3            1                 57   ...                      0        0
4            0                 64   ...                      0        0

[5 rows x 84 columns]

In [130]:
df = one_hot_data.copy()
df.describe()

Goal Scored     ...         PSO_Yes
count   128.000000     ...      128.000000
mean      1.320312     ...        0.062500
std       1.156519     ...        0.243013
min       0.000000     ...        0.000000
25%       0.000000     ...        0.000000
50%       1.000000     ...        0.000000
75%       2.000000     ...        0.000000
max       6.000000     ...        1.000000

[8 rows x 84 columns]

In [131]:
df = df.apply(LabelEncoder().fit_transform)
df.head()

Goal Scored  Ball Possession %   ...     Round_Semi- Finals  PSO_Yes
0            5                 11   ...                      0        0
1            0                 31   ...                      0        0
2            0                 14   ...                      0        0
3            1                 28   ...                      0        0
4            0                 35   ...                      0        0

[5 rows x 84 columns]

# Selecting Label and Features

In [132]:
label = df['Man of the Match_Yes']

features = df.drop(['Man of the Match_Yes'], axis = 1)

# Splitting the Data into training and testing by 20%

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(features, label, test_size = 0.20, random_state =0) 

# Decision Tree Classifier

In [147]:
clf_gini = DecisionTreeClassifier(criterion = "gini", random_state = 100,max_depth=3, min_samples_leaf=5) 
clf_gini.fit(X_train, y_train)


DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=3,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=5, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=100,
            splitter='best')

In [148]:
y_pred = clf_gini.predict(X_test) 
print("Predicted values:") 
print(y_pred) 
    
cal_accuracy(y_test, y_pred)

Predicted values:
[1 1 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 1 1 1 0 1 1 0 0]
Confusion Matrix:  [[ 4  7]
 [ 3 12]]
Accuracy :  61.53846153846154
Report :                precision    recall  f1-score   support

           0       0.57      0.36      0.44        11
           1       0.63      0.80      0.71        15

   micro avg       0.62      0.62      0.62        26
   macro avg       0.60      0.58      0.58        26
weighted avg       0.61      0.62      0.60        26



In [135]:
y_pred = clf_gini.predict(X_train) 
print("Predicted values:") 
print(y_pred) 
    
cal_accuracy(y_train, y_pred)

Predicted values:
[1 0 0 0 1 0 1 0 0 1 1 1 1 0 0 1 1 0 0 0 1 1 0 1 0 0 1 1 1 1 0 1 0 1 1 0 1
 1 0 1 0 1 1 0 1 1 1 1 1 0 0 0 1 0 1 1 0 1 1 1 1 1 1 0 1 0 1 1 1 0 1 1 1 0
 1 0 0 0 0 1 1 1 1 0 1 0 1 0 1 1 1 1 1 1 0 0 0 1 1 1 0 0]
Confusion Matrix:  [[38 15]
 [ 3 46]]
Accuracy :  82.35294117647058
Report :                precision    recall  f1-score   support

           0       0.93      0.72      0.81        53
           1       0.75      0.94      0.84        49

   micro avg       0.82      0.82      0.82       102
   macro avg       0.84      0.83      0.82       102
weighted avg       0.84      0.82      0.82       102



# Cross Validation of Decesion Tree

In [154]:
scores = cross_val_score(clf_gini, features, label, cv=5)
scores  

array([0.76923077, 0.73076923, 0.65384615, 0.73076923, 0.70833333])

In [136]:
one_hot_data.head()

Goal Scored  Ball Possession %   ...     Round_Semi- Finals  PSO_Yes
0            5                 40   ...                      0        0
1            0                 60   ...                      0        0
2            0                 43   ...                      0        0
3            1                 57   ...                      0        0
4            0                 64   ...                      0        0

[5 rows x 84 columns]

# Gaussion Naive Bayes

In [138]:
model = GaussianNB()
model.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [139]:
y_pred = model.predict(X_test)
cal_accuracy(y_test, y_pred)

Confusion Matrix:  [[ 3  8]
 [ 5 10]]
Accuracy :  50.0
Report :                precision    recall  f1-score   support

           0       0.38      0.27      0.32        11
           1       0.56      0.67      0.61        15

   micro avg       0.50      0.50      0.50        26
   macro avg       0.47      0.47      0.46        26
weighted avg       0.48      0.50      0.48        26



In [140]:
y_pred = model.predict(X_train)
cal_accuracy(y_train, y_pred)

Confusion Matrix:  [[42 11]
 [ 2 47]]
Accuracy :  87.25490196078431
Report :                precision    recall  f1-score   support

           0       0.95      0.79      0.87        53
           1       0.81      0.96      0.88        49

   micro avg       0.87      0.87      0.87       102
   macro avg       0.88      0.88      0.87       102
weighted avg       0.89      0.87      0.87       102



# cross validation of Naive Bayes

In [153]:
scores = cross_val_score(model, features, label, cv=5)
scores  

array([0.73076923, 0.65384615, 0.53846154, 0.5       , 0.75      ])

# Random Forest

In [142]:
clf = RandomForestClassifier(n_estimators=100, max_depth=1,random_state=0)
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=1, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [143]:
y_pred=clf.predict(X_test)
cal_accuracy(y_test, y_pred)

Confusion Matrix:  [[ 8  3]
 [ 5 10]]
Accuracy :  69.23076923076923
Report :                precision    recall  f1-score   support

           0       0.62      0.73      0.67        11
           1       0.77      0.67      0.71        15

   micro avg       0.69      0.69      0.69        26
   macro avg       0.69      0.70      0.69        26
weighted avg       0.70      0.69      0.69        26



In [144]:
y_pred=clf.predict(X_train)
cal_accuracy(y_train, y_pred)

Confusion Matrix:  [[47  6]
 [14 35]]
Accuracy :  80.3921568627451
Report :                precision    recall  f1-score   support

           0       0.77      0.89      0.82        53
           1       0.85      0.71      0.78        49

   micro avg       0.80      0.80      0.80       102
   macro avg       0.81      0.80      0.80       102
weighted avg       0.81      0.80      0.80       102



# Cross Validation of Random Forest

In [152]:
scores = cross_val_score(clf, features, label, cv=5)
scores  

array([0.80769231, 0.80769231, 0.61538462, 0.57692308, 0.625     ])

# Conclusion

In [155]:
models = pd.DataFrame({
        'Model'          : ['Naive Bayes',  'Decision Tree', 'Random Forest'],
        'Training_Score' : [model.score(X_train,y_train),  clf_gini.score(X_train,y_train), clf.score(X_train,y_train)],
        'Testing_Score'  : [model.score(X_test,y_test), clf_gini.score(X_test,y_test), clf.score(X_test,y_test)]
    })
models.sort_values(by='Testing_Score', ascending=False)

Model  Training_Score  Testing_Score
2  Random Forest        0.803922       0.692308
1  Decision Tree        0.823529       0.615385
0    Naive Bayes        0.872549       0.500000